### ISSUE TITLE
Duplicated rows in IOEVENTS

### ISSUE THREAD

**Issue by vjm261** [MIT-LCP/mimic-code#12] opened 2015-10-21 15:59 UTC
It appears that many events are duplicated many times (up to 24 times). 

![image](https://cloud.githubusercontent.com/assets/14168103/10642144/61b88292-77ea-11e5-8aff-fd8993c6d6d1.png)

This figure shows the same order, by ORDER ID, listed 24 times with identical fields. I strongly doubt that 24 * 204 mL was actually given. In an even more extreme case 5000mL is given 9 times at the same time.

![image](https://cloud.githubusercontent.com/assets/14168103/10642213/9cff2acc-77ea-11e5-8bfa-98046b538702.png)

These are not cases where the order is split over multiple rows and the component volumes total the ordered volume. These and all of the other cases of 2 or 3 duplicates I have inspected have been perfect replicates.

I suggest this issue should be addressed in the next build and release. In the mean time, care should be taken to filter by unique ORDERID before any summation.

**Comment by alistairewj** [comment] 2015-10-21 19:42
Good catch - this will actually be fixed in the next release. The cause was a single caregiver having multiple IDs - we coalesced these into a single identifier, but this join unintentionally duplicated rows. This primarily affects IOEVENTS because most of those observations have `CGID`, but it also had an impact on NOTEEVENTS, CHARTEVENTS, and DATETIMEEVENTS. The next release, which is imminent, will correct this.

**Comment by alistairewj** [comment] 2015-11-19 14:52
A new version, MIMIC-III v1.2, has been released. This bug is fixed in that version and I recommend you update your data if you haven't already. Thanks for the report!

**Closed by alistairewj** 2015-11-19 14:52 UTC
Labels: bug
