### ISSUE TITLE
labfirstday and vitalfirstday with no results

### ISSUE THREAD

**Issue by alexandreliborio** [MIT-LCP/mimic-code#99] opened 2016-06-10 20:33 UTC
Dear, I've run both querys in PGADM III and display`" Query returned successfully with no result in 265 ms."
Best

**Comment by tompollard** [comment] 2016-06-10 20:37
Hi, this is a duplicate of https://github.com/MIT-LCP/mimic-code/issues/97

**Closed by tompollard** 2016-06-10 20:37 UTC
