### ISSUE TITLE
MIMIC Database not accesible from Ipython

### ISSUE THREAD

**Issue by phoenigmatic** [MIT-LCP/mimic-code#335] opened 2017-11-25 21:33 UTC
I am trying to query that mimic database from a Ipython interface and it keep giving error that the tables(relations) does not exist, however, when I try to query it from the command line it shows perfectly well. Can someone help? I need to reduce the dataset as soon as possible in order to use it on WEKA.

**Comment by tompollard** [comment] 2017-11-26 06:00
There isn't much detail here for us to go on. It sounds like you are successfully creating a database connection, but are not querying the correct database. Most likely you are not specifying the schema in your query.

Try taking a look at the demo notebooks in the code repository for sample code. e.g.: https://github.com/MIT-LCP/mimic-code/blob/master/notebooks/ipynb_example/icu_length_of_stay.ipynb

I'll close this issue for now, but if you still have trouble connecting to the database after following the sample code then please reopen this issue and post the code that you are using to connect.

**Closed by tompollard** 2017-11-26 06:00 UTC

**Comment by waqaraziz123** [comment] 2018-01-22 21:49
Hi, 

I am trying to access MIMIC-III through python but it is not connecting. I can access mimic through sql command prompt though but stuck with this thing.  The error is:

_OperationalError: FATAL:  database "mimic" does not exist_

`
import psycopg2
user = 'postgres'
password = 'postgres'
dbname = 'mimic'
schema = 'mimiciii'
host = 'localhost'

query_schema = 'SET search_path to ' + schema + ';'

con = psycopg2.connect(dbname=dbname, user=user, password=password, host=host)`

I am using Python 2.7 and psql (9.3.20).

Thanks

**Comment by steph409** [comment] 2018-01-22 21:54
hey, 
I think you are missing the little quotes around the database name, the user and the password. Here is my connection string:

` # Define our connection string
    conn_string = "dbname='mimic'  user='elsa', password='password' "
psycopg2.connect(conn_string)
`
does this work for you? :)




  

this is my code to connect.

**Comment by waqaraziz123** [comment] 2018-01-22 22:12
Hi, 

Thank you. I am trying this code right now:

`import psycopg2
user = 'postgres'
password = 'postgres'
dbname = 'mimic'
schema = 'mimiciii'
host = 'localhost'

query_schema = 'SET search_path to ' + schema + ';'

con = psycopg2.connect("dbname=dbname, user=user, password=password, host=host")`

The error is changed into: _OperationalError: could not translate host name "host" to address: Unknown host_

Thanks

**Comment by steph409** [comment] 2018-01-22 22:21
Now the problem is that the user after the = is not interpreted anymore as the variable you defined before but as the string "user".
the easiest way is not to use variables before but to write it directly into the connection string (see post above). 
If you want to use your variables: 
`import psycopg2`
`user = 'postgres'`
`password = 'postgres'`
`dbname = 'mimic'`
`schema = 'mimiciii'`
`host = 'localhost'`

`query_schema = 'SET search_path to ' + schema + ';'`

`con = psycopg2.connect(dbname='+ '\'' + dbname + '\', user=\'' + user + '\', password=\'' + password + '\', host=\' + host'\')`
The backslashes make python interpret the next sign (') as ' and not as end or beginning of the string

**Comment by waqaraziz123** [comment] 2018-01-22 23:14
Hi,

Thank you for your promopt response. The original error _(database "mimic" does not exist)_ is back with this code:

`
import psycopg2
schema = 'mimiciii'
query_schema = 'SET search_path to ' + schema + ';'
conn_string = "dbname='mimic' user='postgres' password='postgres' host='localhost'"
conn = psycopg2.connect(conn_string)
`
Can you see any error ?

thanks

**Comment by steph409** [comment] 2018-01-23 08:49
hey :)
I'm on python 3.6, there it works for me like this. I do not need the localhost in the connection_string. I do not have a password set, but it should work the same. I do not see any error at your code, maybe someone else could help?

Here is my code again:

```
import psycopg2
import pandas as pd


def connectdb():
    # Define our connection string
    conn_string = "dbname='mimic'  user='elsa'"
    print("Connecting to database: ", conn_string)

    # get a connection, if a connect cannot be made an exception will be raised here
    try:
        conn = psycopg2.connect(conn_string)
        conn.autocommit = True
        # psycopg2 creates a server-side cursor, which prevents all of the
        # records from being downloaded at once from the server.
        cursor = conn.cursor()
        print("Successful!\n")
        cursor.execute("SET search_path TO mimiciii")
        return cursor
    except:
        print('Cannot connect to database!')
        return None


if __name__ == "__main__":
    c = connectdb()


  ```

**Comment by tompollard** [comment] 2018-01-23 14:57
@waqaraziz123 The error message "OperationalError: FATAL: database "mimic" does not exist" indicates that a database called "mimic" cannot be found. There is nothing to suggest this is a syntax issue, so I would suggest sticking with your original code. 

There could be several reasons for the error (e.g. you do not have a database called mimic on your system, the database is not at 'localhost', there is a permission issue, etc). What is your operating system?

**Comment by waqaraziz123** [comment] 2018-01-23 20:50
Hi, 

I am using Windows 10 and database is running fine on command prompt and pgadmin. Database is at localhost by default setting:

![sql shell](https://user-images.githubusercontent.com/34290579/35299939-ccd015ea-00eb-11e8-8a3a-a5ce5dad409c.jpg)

I am running Python script via Spyder (Anaconda). Is this can be the issue ?

Thanks

**Comment by alistairewj** [comment] 2018-01-24 00:29
Your database name is 'postgres', not 'mimic'.

**Comment by waqaraziz123** [comment] 2018-01-28 20:52
Hi, 
The problem was related with two different versions of PSQL available on system. I have installed PSQL 10.1 first and then also installed 9.3 and build MIMIC on it. The default port for 10.1 is '5432' and 9.3 is '5433'. When Python code was trying to connect with PSQL, it was by default calling port '5432' as there was no database available on version 10.1, that's why giving error "mimic" doesn't exisit. 

I uninstalled version 10.1 but still python was unable to connect. So, I have to uninstall both versions and re-installed PSQL 10.1, build MIMIC again and it is working fine.

Thank you @tompollard , @alistairewj and @steph409.

**Comment by tompollard** [comment] 2018-01-30 22:00
@waqaraziz123 glad to hear you solved the issue.

> The default port for 10.1 is '5432' and 9.3 is '5433'.

The default port is `5432` for all versions as far as I'm aware. When you installed 9.3 it was assigned port `5433`, because `5432` was already taken.

**Comment by waqaraziz123** [comment] 2018-01-30 22:11
Yeah, probabaly. One thing I observed during re-installation that it took around two days to install although previosuly it was installed overnight.
