### ISSUE TITLE
Where can I access the source data used in the Medfuse "multimodal fusion" paper?

### ISSUE THREAD

**Issue by AmudhaTK** [MIT-LCP/mimic-code#1431] opened 2022-11-25 14:42 UTC
OOPs something went wrong. sorry please see the below query.

**Comment by tompollard** [comment] 2022-11-26 03:52
@AmudhaTK It's unclear what is being asked here. The title is unclear and the content of the issue is empty (other than the template text). Please reopen if you are able to provide a more complete description of the issue.

**Comment by AmudhaTK** [comment] 2022-11-28 17:48
@tompollard I have read the paper titled Medfuse: Multimodal fusion with Clinical time series data and Chest X-ray image. In that they discussed about clinical time series data. In that article, they mentioned  that data is available in the MIMIC-EXTRACTED folder in their GitHub Link.  But unfortunately, that folder is not available and also its associated CSV files also missing. So please can you guide inthat references. How to get the test_listifile.CSV and val_listfile.CSV? I am interested in doing my research using multimodal fusion with more than 2 modalities. Any leads for the same

[2207.07027v1.pdf](https://github.com/MIT-LCP/mimic-code/files/10106162/2207.07027v1.pdf)

**Comment by AmudhaTK** [comment] 2022-11-28 17:49
> @AmudhaTK It's unclear what is being asked here. The title is unclear and the content of the issue is empty (other than the template text). Please reopen if you are able to provide a more complete description of the issue.

**Comment by tompollard** [comment] 2022-11-28 20:18
I have messaged the creators of the project, who I hope will respond. For the meantime, I believe you can use their codebase at https://github.com/nyuad-cai/MedFuse to generate the extracted data from the source MIMIC datasets.

- https://physionet.org/content/mimic-cxr/
- https://physionet.org/content/mimiciv/

You'll need to ensure that you are using the correct versions of the datasets, which I hope are specified in the project. You can view different versions of the projects in the "Versions" box on the right hand side of the project page.

**Comment by AmudhaTK** [comment] 2022-11-29 07:17
I have thoroughly checked each and every folders/file of mimic-cxr and mimic-iv, but i couldn't found it (val_listfile.csv and test_listfile.csv). Any update from the creators of the project? pls let me know

**Comment by farahshamout** [comment] 2022-11-29 08:07
@AmudhaTK Please follow the steps here to generate the splits for MIMIC-IV: https://github.com/nyuad-cai/MedFuse/blob/main/mimic4extract/README.md

**Comment by AmudhaTK** [comment] 2022-11-29 17:42
@farahshamout Thank you will try the steps which you have mentioned in README.md.

**Comment by tompollard** [comment] 2022-11-29 17:58
Thanks @farahshamout! @AmudhaTK, let us know how you get on.

**Comment by AmudhaTK** [comment] 2022-12-07 08:14
I got MIMIcC-CXR files but how to get MIMIC-IV-EHR  files.?

**Comment by briangow** [comment] 2022-12-09 19:13
@AmudhaTK , I believe the MIMIC-IV-EHR files you are looking for can be found in the MIMIC-IV project on PhysioNet: https://physionet.org/content/mimiciv/1.0/ . As mentioned above you should make sure to select the correct version of the project on the right before downloading the CSV's.

**Comment by AmudhaTK** [comment] 2022-12-10 15:02
@briangow , Sorry to say this, I couldn't able to get the CSV's of MIMIC-IV-EHR  from the MIMICiv/1.0 (Repository).https://physionet.org/content/mimiciv/1.0. Is it possible to get the proper CSV of MIMIC-IV-EHR ?

**Comment by marymlucas** [comment] 2022-12-10 16:33
Hi Amudha
When I log into the link you posted for v1 of MIMIC-IV and scroll to the bottom and click ICU, this is what I see. These are the gzipped CSV files. Do you not see the same?

![MIMIC-IV_v1_0](https://user-images.githubusercontent.com/34073785/206865160-117ce5ff-65fa-40a7-bf7f-c3c22812862b.jpg)

**Comment by AmudhaTK** [comment] 2022-12-11 10:12
HI @marymlucas . I am a credential user of physionet.  I have thoroughly checked each and every folders/file of mimic-cxr and mimic-iv, but i couldn't found it (val_listfile.csv and test_listfile.csv). I already received from @farahshamout that i should follow the Readme.md file of MIMIC-IV extracted. But then i couldn't able to get the val_listfile.csv and test_listfile.csv , if I run the code in colab. pls let me know how to proceed further. 
![mimic4extract](https://user-images.githubusercontent.com/95337672/206897714-1b6dfaba-e9a8-4e2b-805e-f8aa4dfbad63.jpg)

**Comment by marymlucas** [comment] 2022-12-11 16:18
Hi @AmudhaTK 
OK, I understand your question now.  Here is my opinion.

Because these two files _val_listfile.csv_ and _test_listfile.csv_ are NOT part of the MIMIC-IV EHR you're not going to find them in the repository.  You have to generate them yourself from the MedFuse code, so it's hard for anyone to help directly. 

My suggestion would be to run the code specified on the MedFuse github repo to generate the files and then go through any error messages you get and try to troubleshoot them one by one. Sometimes it's just something simple like file paths set incorrectly and sometimes you have to tweak some of the code to make it work in your environment. I run into these kinds of issues frequently when trying to replicate studies and it can be very frustrating. I find I get more helpful replies and guidance once I have tried the code myself, fixed any issues I can, and then have very specific errors I can ask for help with from the code authors.

Hope this helps.

Mary

**Comment by AmudhaTK** [comment] 2022-12-12 08:13
Thank you @marymlucas for your guidance.  Let me try with what you have suggested. If I need any help, will ask you for the same.

**Comment by AmudhaTK** [comment] 2023-01-16 13:37
Hi all,
 May i know how much memory is needed for the dataset storage and for execution of the program (to Run the code) ? So that i request my institution for the same.

**Comment by AmudhaTK** [comment] 2023-01-28 02:06
Hi @farahshamout  ,
May i know how much memory is needed for the dataset storage + for execution of the program (to Run the code) ? So that i request my institution for the same.

**Comment by alistairewj** [comment] 2023-02-04 01:31
Going to close this since it's not related to MIMIC-code - @AmudhaTK I recommend you raise an issue over at https://github.com/nyuad-cai/MedFuse

For what it's worth, MIMIC-IV is around 8gb compressed, MIMIC-CXR can be 500gb for the JPGs, or it can be 5 TB for the DICOMs, so the answer to the question heavily depends on what MedFuse is doing.

**Closed by alistairewj** 2023-02-04 01:31 UTC

**Comment by AmudhaTK** [comment] 2023-02-04 07:27
Hi @alistairewj, thank you for your direction, I have initiated my conversation with @farahshamout.
