### ISSUE TITLE
Catheterization insertion dates not available

### ISSUE THREAD

**Issue by erjthakur** [MIT-LCP/mimic-code#365] opened 2018-01-10 01:56 UTC
There are 6580 (with 162 positive cases) neonates who have undergone blood culture and were suspected of sepsis.
There are only two item id's in the d_items table that are showing some results.
item id 3670 for UAC tubing change has data for 78 distinct neonates whereas
item id 3671 for UVC tubing change has data for 112 distinct neonates.

The above-mentioned item ids tell us that there was catheter inserted in these neonates.
But the duration for which the catheter was inserted has not been mentioned.

Other items ids for catheter insertion dates have 0 rows.
We are interested in calculating the duration for which the catheter was inserted in neonates.
as this is required in our research to reproduce the results given by Okascharoen et. al. (for prediction of neonatal sepsis)
Is there any other solution (or code ) that you can point us to which can help us in extracting this information.

**Comment by alistairewj** [comment] 2018-01-10 19:04
You can re-open previously closed issues. Please don't open a new issue for the same topic. Duplicate of #361.

**Closed by alistairewj** 2018-01-10 19:04 UTC
