### ISSUE TITLE
Discharge time earlier than the Admission time

### ISSUE THREAD

**Issue by ZiyueC** [MIT-LCP/mimic-code#1288] opened 2022-04-11 03:46 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Hi, I found there are a few ICU stays (65 stays inside MIMIC-IV total of 76540 stays) where their discharge time is earlier than the admission time. I noticed that you said there are inconsistencies as the discharge times are entered administratively. Do you think we should exclude these parts from the models?

Thanks.

**Comment by tompollard** [comment] 2024-01-31 17:04
Duplicate of https://github.com/MIT-LCP/mimic-code/discussions/1702

**Closed by tompollard** 2024-01-31 17:04 UTC
