### ISSUE TITLE
Elixhauser score DRG calculation limit

### ISSUE THREAD

**Issue by joel1391** [MIT-LCP/mimic-code#78] opened 2016-02-17 02:11 UTC
I ran the elixhauser sql code for MIMIC III on postgres (windows) and it works for the first 31,000 rows, but the the next 20,000 scores are empty. The subject-id and hadm_id columns are full, it's just the rest of the row is missing. I looked through the diagnoses_icd table and pretty much all hospital admissions are accompanied by an icd code. 

I believe this is because there are only around 31,000 admissions with a 'HCFA' DRG code type. Is there any way to calculate elixhauser comorbidities using 'MS' or 'APR' DRG code types?

**Comment by alistairewj** [comment] 2016-02-17 02:35
Ah, you know what, I know what the problem is. The code was written before we split HCFA into 'HCFA' DRGs and 'MS' DRGs. The old code assumes everything is still labelled as 'HCFA'. Unfortunately, it's not as simple as just adding 'MS' to the list since all the codes are different!

As a temporary solution, I would remove the DRGs entirely (by setting all those features to 0). They are a filter meant to catch comorbidities which were actually the main diagnosis. I have 3-4 versions of Elixhauser which we were going to go over in the lab but haven't had the chance yet - will keep you posted.

**Comment by alistairewj** [comment] 2016-02-18 22:05
Hey @joel1391 - I just uploaded some code which implements Elixhauser using the AHRQ definitions. Can you give it a go and see if everything works on your end? I hard coded the schema names as "mimiciii" - something to watch out for if you have your data on a different schema name.

**Comment by joel1391** [comment] 2016-02-19 00:14
Thanks @alistairewj ! It works great, no missing values this time.
I just had to change the first line to DROP MATERIALIZED VIEW IF EXISTS to get it to work first time around. I added a few other instances of subject_id in the query to include it in the view, and I put in a pull request. I'm new to github so apologies if I didn't submit it properly..

**Comment by alistairewj** [comment] 2016-02-19 00:34
Awesome. In theory you should be able to keep the DROP MATERIALIZED VIEW IF EXISTS - postgres will just throw out a warning to say the view doesn't exist and carry on (I run the scripts using \i and this is what happens for me). I just merged your pull request though I updated it afterward to swap the order of subject_id/hadm_id because I am pedantic :) I'll remove the old elixhauser code and close the issue now.

**Closed** 2016-02-19 00:34 UTC
