### ISSUE TITLE
Load MIMIC-IV（v1.0） into a PostgreSQL database Error

### ISSUE THREAD

**Issue by zhaoxiongjun** [MIT-LCP/mimic-code#1353] opened 2022-08-02 01:20 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

When I create the schema for MIMIC-IV（v1.0) and load the data into the appropriate tables for PostgreSQL, Then when executing the **constraint.sql** file, the following error occurs:.

`psql:constraint.sql:236: ERROR:  insert or update on table "diagnoses_icd" violates foreign key constraint "diagnoses_icd_admissions_fk"
DETAIL:  Key (hadm_id)=(20826040) is not present in table "admissions".`

The code version what I use is `https://github.com/MIT-LCP/mimic-iv/tree/master/buildmimic/postgres`, But I think it's a data problem, not a code version problem.  Should I ditch v1.0 and use MIMIC-IV v2.0.  Is it possible to solve this, because I need to use V1.0 for comparative experiments, and there may be unfair comparisons using V2.0.

**Comment by alistairewj** [comment] 2022-08-12 13:28
This is a duplicate of #1071

Essentially, there are ~3 `hadm_id` which are in the *diagnoses_icd* table but not in the *admissions* table, as we had a filter applied to the *admissions* table but not billed diagnoses table. We fixed this in MIMIC-IV v2.0. You really shouldn't see any appreciable difference in the comparison. You won't need the constraint to conduct your analysis, it just verified data integrity.

**Closed** 2022-08-12 13:30 UTC
Labels: duplicate, mimic-iv
