### ISSUE TITLE
Potential issue in date shifting - PATIENTS table

### ISSUE THREAD

**Issue by vjm261** [MIT-LCP/mimic-code#7] opened 2015-10-09 17:32 UTC
It appears that six rows of the PATIENTS table have the real, 20th century, patient DOB. I assume these values have not been data shifted with the corresponding DODs because otherwise they yield ages at admission of 200+ years.

Six cases identified below:
![image](https://cloud.githubusercontent.com/assets/14168103/10400856/5b87edd2-6e89-11e5-8c4a-afaa48852ce5.png)

Bug fix for the next build.

**Comment by alistairewj** [comment] 2015-10-09 17:47
This is intended behaviour. If a patient is older than 89 years old, their DOB is set so that their age at their first hospital admission is 200. So while the DOBs are listed as occurring in this century, I can promise you that they are not the true patient DOBs.

There's an obvious trade off here: it's confusing for users to have ages greater than 200, but it was hoped that the confusion is warranted so that users don't accidentally ignore this important aspect of the anonymization process. May be worth further discussion - we could perhaps set these DOBs to NULL instead. I will close this for now - but feel free to add any feedback you have. Thanks for the report!

**Closed by alistairewj** 2015-10-09 17:47 UTC

**Comment by vjm261** [comment] 2015-10-09 20:33
Thank you Alistair. I remember reading this but it slipped my mind at the time.

**Comment by parisni** [comment] 2017-06-12 19:34
>  we could perhaps set these DOBs to NULL instead.

Sounds like replace with NULLs is better way of doing. This is quite confusing while every user finally remove the DOB. Result would be the same while being less error prone for users ?

**Comment by tompollard** [comment] 2017-06-12 20:13
@parisni setting the dob to NULL presents is likely to confuse people too, as you say. 

If we take your suggestion of adding an `age_at_last_admit` field, then we would need to decide how to deal with charted times etc which are currently anchored to the `dob`. 

I like the [eICU collaborative research database](http://eicu-crd.mit.edu/) approach, which takes the time of first admission as the anchor for charted times. Ages can then be specified as you suggest (e.g. ">89").

**Comment by parisni** [comment] 2017-06-13 17:55
> how to deal with charted times etc which are currently anchored to the dob.

@tompollard  can you please provide me an example of such case where a charttime is anchored to dob ?

Thanks !
