### ISSUE TITLE
mismatch between PRESCRIPTIONS and TRANSFERS?

### ISSUE THREAD

**Issue by sibipx** [MIT-LCP/mimic-code#345] opened 2017-12-03 01:47 UTC
Hi!

First, thank you for sharing such a comprehensive medical dataset!

I am interested in studying of the ICU medication prescriptions, but I have difficulty in understanding what looks like mismatches between the PRESCRIPTIONS and the TRANSFERS tables.

For the moment, I am focusing on the drugs prescribed in the first day of an admission (which I will call: prescriptions at T0)

Out of the 50211 admissions (distinct HADM_ID) with prescriptions:
- (type I) 21.23% have the prescription lines at T0 linked to a hospital stay (non-ICU stay) while at the moment of prescription (STARTDATE) the patient is located in an ICU ward (the corresponding stay for that day in TRANSFERS is an ICU stay). A hospital stay / transfer exists though for these admissions / HADM_ID (in the future compared to T0, of course)
	e.g.: HADM_ID: 177610, 175992, 180923, ...
- (type II) 7.05% have the prescription lines at T0 linked to a hospital stay (non-ICU stay) while no hospital stay exists at all in the TRANSFERS table for the current admission (the patients seems to be admitted and discharged from ICU)
	e.g.: HADM_ID: 162416, 174212, 136559
- (type III) 0.36% have prescription lines at T0 linked to an ICU stay while the patient in not located in an ICU ward. Here I see a trend: mainly Neonatal ward stay that follows a Neonatal ICU stay, and prescription lines linked to an ICU stay that is not part of the current admission (HADM_ID), but of a previous admission of the same patient
	e.g.: HADM_ID: 121197, 162882, 130712
- (type IV, for the sake of completeness) ~ 0% have prescription lines at T0 linked to an ICU stay while no ICU stay exists  (2 cases) - not of my worry

I call a "hospital stay" a record in the TRANSFERS table (of EVENTTYPE admit or transfer) for which the ICUSTAY_ID is null.

Some hints / questions / possible explanations that came to my mind:

- are some drugs prescribed retroactively (as in: they were administered anyhow, so a prescription was placed in the system after the effective date/time)? or taken over from a previous admission? Is the STARTDATE in fact the date when a prescription is placed in the system (as in STORETIME for other tables) or the planned STARTDATE of the scheduled plan for drug administration?
- #120 reports some ICU stay - HADM_ID mismatch for another table, but it's fixed in v1.4 (on which I am currently working), and maybe not fully related
- From the documentation of the SERVICES table: "While a patient can be physically located at a given ICU type (say MICU), they are not necessarily being cared for by the team which staffs the MICU. This can happen due to a number of reasons, including bed shortage." This is a nice explanation, but I would want to know if this really explains the cases above.

Although I did not look into many of the other tables, I had a quick check on OUTPUTEVENTS table (CHARTTIME) vs. TRANSFERS, and no such mismatch of such magnitude exists there.

It would really help me to understand these (apparent) mismatched links between PRESCRIPTIONS and TRANSFERS tables, to be able to make a subset that I understand.

To support the claims above, I could share R code (and eventually a shiny app to visualize the prescription lines). I did not build a database (as I don't necessarily need it), but if strictly needed to provide queries, I could still build it. Just let me know if you need extra information and how could I share it.

Thank you!

Elena

**Comment by alistairewj** [comment] 2017-12-03 20:04
Thanks Elena, glad to see you find the data useful.

It's a bit hard to understand exactly the issue but perhaps some discussion on the nature of the TRANSFERS and PRESCRIPTIONS tables will help. TRANSFERS is a patient tracking table which informs you of where the patient is in the hospital. Let's look at an example:

```sql
select hadm_id, icustay_id, eventtype, curr_careunit, curr_wardid
, to_char(intime,'MM-DD HH24:MI') as intime, to_char(outtime,'MM-DD HH24:MI') as outtime
from transfers
where hadm_id = 114585;
```


 hadm_id | icustay_id | eventtype | curr_careunit | curr_wardid |   intime    |   outtime   
--------- | ------------ | ----------- | --------------- | ------------- | ------------- | -------------
  114585 |            | admit     |               |          54 | 10-16 12:49 | 10-17 13:22
  114585 |     232514 | transfer  | SICU          |          57 | 10-17 13:22 | 10-24 16:26
  114585 |            | transfer  |               |          54 | 10-24 16:26 | 11-03 13:00
  114585 |            | transfer  |               |          54 | 11-03 13:00 | 11-13 16:54
  114585 |            | discharge |               |             | 11-13 16:54 | 

(Note above, hours use a 24 hour clock, so 13:22 is 1:22 PM).

Here we see one hospitalization for a patient. The patient is admitted to the hospital on `10-16` at `12:49`. They are admitted to some area of the hospital, `curr_wardid = 54`. We could imagine this is a general ward. At `10-17 13:22` she is transferred from that ward to the ICU (a Surgical ICU or SICU, as denoted by `curr_careunit`). She stays in the SICU for 7 days, and afterwards is transferred to the same area of the hospital, `curr_wardid = 54`. She stays there for another week and a half, and is discharged from the hospital on `11-13` at 16:54 (5pm). TRANSFERS table tells us how a patient moves throughout a hospital. Referring to a single row of this table as a "hospital stay" as you propose is a bit misleading - it's better to refer to a single row as a ward or unit stay, as all rows associated with a single `hadm_id` comprise the hospital stay.

If we look at her prescriptions 

```sql
select hadm_id, to_char(startdate, 'MM-DD HH24:MI') as startdate
, drug, dose_val_rx || ' ' || dose_unit_rx as dose
, route
from prescriptions where hadm_id = 114585
order by startdate
```

We would see a very large table (261 rows), here is a snippet of the beginning and the end:

 hadm_id |  startdate  |               drug                |    dose     |  route  
--------- | ------------- | ----------------------------------- | ------------- | ---------
  114585 | 10-16 00:00 | D5 1/2NS                          | 1000 ml     | IV
  114585 | 10-16 00:00 | Hydrocortisone Na Succ.           | 100 mg      | IV
  114585 | 10-16 00:00 | Hydrochlorothiazide               | 25 mg       | PO
  114585 | 10-17 00:00 | D5W                               | 250 ml      | IV DRIP
  114585 | 10-17 00:00 | D5W                               | 250 ml      | IV DRIP
  114585 | 10-17 00:00 | Fentanyl Citrate                  | 2.5 mg      | IV DRIP
  114585 | 10-17 00:00 | Propofol                          | 1000 mg     | IV DRIP
... | ... | ... | ... | ... 
  114585 | 11-12 00:00 | Bisacodyl                         | 10 mg       | PR
  114585 | 11-12 00:00 | Warfarin                          | 4 mg        | PO
  114585 | 11-12 00:00 | HydrALAZINE HCl                   | 25 mg       | PO
  114585 | 11-13 00:00 | Warfarin                          | 4 mg        | PO
  114585 | 11-13 00:00 | Bisacodyl                         | 10 mg       | PR

We can see that she is prescribed medications both at the start of her hospital stay (`10-16`) and at the end of her hospital stay (`11-13`). Note also that we don't have *any* time information for these prescriptions, we only know the day they were made. This is why the column is called `startdate`, and *not* called `starttime`.

To answer some of your questions:

> are some drugs prescribed retroactively (as in: they were administered anyhow, so a prescription was placed in the system after the effective date/time)? or taken over from a previous admission? Is the STARTDATE in fact the date when a prescription is placed in the system (as in STORETIME for other tables) or the planned STARTDATE of the scheduled plan for drug administration?

Yes, this is possible. For emergency situations, care providers can administer medications, and retroactively prescribe them to the patient. The `startdate` is the date of prescription: whether planned or retroactively assigned. It is not when the prescription was entered into the system.

> #120 reports some ICU stay - HADM_ID mismatch for another table, but it's fixed in v1.4 (on which I am currently working), and maybe not fully related

I don't think this is related, as you suggest.

> From the documentation of the SERVICES table: "While a patient can be physically located at a given ICU type (say MICU), they are not necessarily being cared for by the team which staffs the MICU. This can happen due to a number of reasons, including bed shortage." This is a nice explanation, but I would want to know if this really explains the cases above.

I don't think this is related either.

Could you elaborate on the issue with my post in mind?

**Comment by sibipx** [comment] 2017-12-03 21:41
Hi Alistair!

Thank your for such a quick reply and for some answers already.

To avoid confusion I will call 
- a hospital-ward stay: a row in the TRANFERS table for which ICUSTAY_ID is null
- an ICU-ward stay:   a row in the TRANFERS table for which ICUSTAY_ID is NOT NULL
Note: I do not look at the CURR_WARDID (I did read somewhere that some codes changed over time) but anyhow for now I will not refer to the exact location (ward code) at all, I am only looking at the link in between the prescription lines and ICUSTAY_ID

Let's take my second example - HADM_ID: 175992 - I think it's one easy to follow.

Query on TRANSFERS table (more or less same as you posted, but with HADM_ID: 175992

```sql
select hadm_id, icustay_id, eventtype, 
, to_char(intime,'MM-DD HH24:MI') as intime, to_char(outtime,'MM-DD HH24:MI') as outtime
from transfers
where hadm_id = 175992;
```
should give something similar to this:

```
  HADM_ID ICUSTAY_ID EVENTTYPE      INTIME     OUTTIME
1  175992     208758     admit 08-18 16:33 08-20 18:02
2  175992         NA  transfer 08-20 18:02 08-21 14:50
3  175992         NA  transfer 08-21 14:50 08-22 17:09
4  175992         NA discharge 08-22 17:09           
```

The patient has been admitted to an ICU-ward on 2134-08-18 16:33:22 and the patient is transferred to a hospital-ward on  2134-08-20 18:02:08 (~ 2 days later)

Let's look at prescriptions. Please add ICUSTAY_ID in the query as well.

If we order by STARTDATE we see that the first prescription lines start on 2134-08-18, the same date as the admission start (I am aware that there is no time for prescription lines).

```sql
select hadm_id, ICUSTAY_ID, to_char(startdate, 'MM-DD HH24:MI') as startdate
, drug, dose_val_rx, route
from prescriptions where hadm_id = 175992
order by startdate
```
should give something like:

```
   HADM_ID ICUSTAY_ID   STARTDATE                                DRUG DOSE_VAL_RX ROUTE
1   175992         NA 08-18 00:00                          Omeprazole          20    PO
2   175992         NA 08-18 00:00         Pneumococcal Vac Polyvalent         0.5    IM
3   175992         NA 08-18 00:00                               Senna           1    PO
4   175992         NA 08-18 00:00                           Bisacodyl          10    PO
5   175992         NA 08-18 00:00                           Bisacodyl          10    PR
6   175992         NA 08-18 00:00                             Heparin        5000    SC
7   175992         NA 08-18 00:00                        Atorvastatin          80 PO/NG
8   175992         NA 08-18 00:00                  Losartan Potassium          50 PO/NG
9   175992         NA 08-18 00:00                         Clopidogrel          75    PO
10  175992         NA 08-18 00:00                          Aspirin EC         325    PO
11  175992         NA 08-18 00:00                 Metoprolol Tartrate        12.5 PO/NG
12  175992         NA 08-18 00:00                          Citalopram          20 PO/NG
13  175992     208758 08-19 00:00                       Acetaminophen    500-1000 PO/NG
14  175992     208758 08-20 00:00                          Vancomycin        1000    IV
15  175992     208758 08-20 00:00                Iso-Osmotic Dextrose         200    IV
16  175992     208758 08-20 00:00 Oxycodone-Acetaminophen (5mg-325mg)         1-2    PO
17  175992     208758 08-20 00:00                          Vancomycin        1000    IV
18  175992     208758 08-20 00:00                Iso-Osmotic Dextrose         200    IV
19  175992     208758 08-20 00:00      OxycoDONE (Immediate Release)            5 PO/NG
20  175992     208758 08-20 00:00         Sodium Chloride 0.9%  Flush           3    IV
21  175992     208758 08-20 00:00                          Omeprazole          40    PO
22  175992     208758 08-21 00:00                          Cephalexin         500 PO/NG
```

All these lines starting on 2134-08-18 are not linked to ICUSTAY_ID 208758.
_**My question is: why?**_ On this date the patient stay is linked to ICUSTAY_ID 208758, but all prescription lines are not. 

Then, there is one line on 2134-08-18 linked to ICUSTAY_ID 208758 - that's fine.
Then, the prescription lines that start on 2134-08-20 are linked to ICUSTAY_ID 208758 - fine for me as well.
Then, on 2134-08-21, a prescription line started for Cephalexin (which is not a continuation of another prescription line for Cephalexin!), linked to ICUSTAY_ID 208758 (but the patient is not located anymore in an ICU-ward since 2134-08-20) - debatable if this is a mismatch or not...

In any case, my focus now is on first prescription lines, with startdate in the first day of the admission. Why are these lines not linked to ICUSTAY_ID? According to my calculation 21.23% of the admissions (for which prescriptions exist) are affected by "no prescription line link to ICUSTAY_ID while the stay in TRANSFERS on the same day is linked to ICUSTAY_ID". In calculating this I do not include "potential mismatches" (as in: in the same day the patient is in an ICU-ward and then in a hospital-ward), but only the cases when on the day of the first prescription lines, the patient does not appear to have a hospital-ward stay.  

The example you have posted (HADM_ID 114585) is fine, no such "mismatch".

Thanks for your support!

**Comment by alistairewj** [comment] 2017-12-04 00:02
Ah, I see. On the page for the icustays table (https://mimic.physionet.org/mimictables/icustays/), it says:

> ICUSTAY_ID is a generated identifier that is not based on any raw data identifier. The hospital and ICU databases are not intrinsically linked and so do not have any concept of an ICU encounter identifier.

What you are observing is a consequence of this. I think the documentation needs an update because I now realize it's not very clear what this means. Essentially, we create a unique ICUSTAY_ID for any patient stay in an ICU (SICU, MICU, etc). If there are two ICU stays for the same patient within 24 hours, we combine these into the same ICUSTAY_ID.

That means that ICUSTAY_ID is *assigned* to the prescriptions table using the intime and the outtime from the transfers table (after grouping by ICUSTAY_ID, which is essentially what the ICUSTAYS table is). That means that the observations on 08-18 are *not* assigned to an ICUSTAY_ID, because `08-18 00:00` < `08-18 16:33`, which is the admission time for the ICU patient. 

This does not fully explain the story - why then does `08-21 00:00` (the last row) get assigned an ICUSTAY_ID, when the patient's `outtime = 08-20 18:02`? Well, we did not actually assign them based on the exact `intime` and `outtime`, but rather extended the times backward or forward 12 hours, e.g. `intime - 12 = 08-18 04:33` and `outtime + 12 = 08-21 06:02`. The last line, Cephalexin, is assigned to the ICUSTAY_ID because `08-21 00:00 < 08-21 06:02` (outtime + 12 hours), while the beginning rows are not because `08-18 00:00 < 08-18 04:33` (intime - 12 hours). This approach was intended alleviate the kind of issue you have seen: data which we know is associated with the patient's ICU stay, but because of slight inconsistencies in timing, doesn't get assigned an ICUSTAY_ID. Unfortunately, this approach isn't foolproof, and we may revisit having an ICUSTAY_ID column in this table in the future.

Finally, you can reproduce the assignment of `ICUSTAY_ID` to this table with the following code:

```sql
with i as
(
  select
    subject_id, icustay_id, intime, outtime
    , lag (outtime) over (partition by subject_id order by intime) as outtime_lag
    , lead (intime) over (partition by subject_id order by intime) as intime_lead
  from icustays
)
, iid_assign as
(
  select
    i.subject_id, i.icustay_id
    -- this rule is:
    --  if there are two hospitalizations within 24 hours, set the start/stop
    --  time as half way between the two admissions
    , case
        when i.outtime_lag is not null
        and i.outtime_lag > (i.intime - interval '24' hour)
          then i.intime - ((i.intime - i.outtime_lag)/2)
      else i.intime - interval '12' hour
      end as data_start
    , case
        when i.intime_lead is not null
        and i.intime_lead < (i.outtime + interval '24' hour)
          then i.outtime + ((i.intime_lead - i.outtime)/2)
      else (i.outtime + interval '12' hour)
      end as data_end
    from i
)
select 
  hadm_id
  , pr.icustay_id -- ICUSTAY_ID from the prescriptions table
  , ia.icustay_id as icustay_id_assigned -- assigned ICUSTAY_ID from views above
  , to_char(startdate, 'MM-DD HH24:MI') as startdate
  , drug, dose_val_rx, route
from prescriptions pr
left join iid_assign ia
  on pr.subject_id = ia.subject_id
  and pr.startdate >= ia.data_start
  and pr.startdate < ia.data_end
where pr.hadm_id = 175992
order by startdate;
```

**Comment by sibipx** [comment] 2017-12-04 15:40
Ok, great that you shared the logic, because that explains a lot!
In fact, it explains all the types of mismatches that I mentioned initially. 

I will go around it either by following the current prescription - ICU stay link and "fixing" the mismatches or by rebuilding the ICU stay - prescription line link logic, similar to what you describe but with different windowing so that it gives less mismatches... I will see...

Just as a note, I think the windowing over subject_id only (and not hadm_id) also creates situations where link ICUSTAY_ID - HADM_ID links are different in PRESCRIPTIONS and TRANSFERS tables. Eg my first example in type III: HADM_ID: 121197 / SUBJECTI_ID: 17112

TRANSFERS:
```
HADM_ID ICUSTAY_ID
138411     280971
```
PRESCRIPTIONS:
```
HADM_ID ICUSTAY_ID
121197     280971
```
TRANSFERS:
```
  SUBJECT_ID HADM_ID ICUSTAY_ID EVENTTYPE              INTIME             OUTTIME
1      17112  138411     280971     admit 2104-12-08 20:59:32 2105-01-09 15:14:50
2      17112  138411         NA discharge 2105-01-09 15:14:50                    
3      17112  121197     206502     admit 2105-01-10 12:35:19 2105-01-16 16:50:20
4      17112  121197         NA discharge 2105-01-16 16:50:20                    
```
PRESCRIPTIONS:
```
   HADM_ID ICUSTAY_ID           STARTDATE                                 DRUG DOSE_VAL_RX   ROUTE
1   121197     280971 2105-01-10 00:00:00              Ipratropium Bromide MDI           2      IH
2   121197     280971 2105-01-10 00:00:00                                Senna           1      PO
3   121197     280971 2105-01-10 00:00:00 Lansoprazole Oral Disintegrating Tab          30      PO
4   121197     280971 2105-01-10 00:00:00             Docusate Sodium (Liquid)         100      PO
5   121197     280971 2105-01-10 00:00:00                              Insulin           0      SC
6   121197     280971 2105-01-10 00:00:00                              Digoxin       0.125      PO
7   121197     280971 2105-01-10 00:00:00                       Amiodarone HCl         200      PO
8   121197     280971 2105-01-10 00:00:00                         Atorvastatin          80      PO
9   121197     280971 2105-01-10 00:00:00                 Levothyroxine Sodium          75      PO
10  121197     280971 2105-01-10 00:00:00    Heparin Flush CVL  (100 units/ml)           1      IV
```

With all this clarified, I am ok to close the issue, except if you feel the need to add anything else or you need any additional information from me?

Thanks!

**Comment by alistairewj** [comment] 2017-12-04 18:00
Hrm, good spot, that's definitely a bug. I'll raise it and we'll fix it for the next release. Happily very short hospital readmissions (<24 hours) are very rare though, so it won't affect too much. Seems we've thoroughly investigated the problem so I'll close this issue - cheers!

**Closed by alistairewj** 2017-12-04 18:00 UTC
