### ISSUE TITLE
Glucose values repeated in labevents and chartevents with 1 hour lag

### ISSUE THREAD

**Issue by oizin** [MIT-LCP/mimic-code#1061] opened 2021-06-08 06:05 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

I've noticed that there are instances of lab glucose measurements being repeated in both chartevents and labevents but separated by one hour. The following query shows an example for one patient. CHARTTIME_LAB_P1 is the lab chartime with an hour added. If you generalise to all admissions you get ~100,000 rows, with most pairs being itemids 220621 and 50931 (both lab so that makes sense). I originally discovered this looking at https://physionet.org/content/glucose-management-mimic/1.0.1/, and verified it in the original data. Is this something that is known about and it is a case of picking the earlier/later time? When I ran the below query on MIMIC-IV I got nothing strange back.

```
select t1.HADM_ID, t1.CHARTTIME AS CHARTTIME_CHART, 
    CHARTTIME_P1 AS CHARTTIME_LAB_P1, 
    t1.STORETIME, t1.ITEMID as ITEMID_CHART, 
    t2.ITEMID as ITEMID_LAB, 
    t1.VALUE as VALUE_CHART, 
    t2.VALUE as VALUE_LAB from
(select HADM_ID,CHARTTIME,STORETIME,VALUE,ITEMID
from `physionet-data.mimiciii_clinical.chartevents`
where icustay_id = 214619 and itemid in (225664,220621)) t1
join
(select HADM_ID,TIMESTAMP_ADD(CHARTTIME, INTERVAL 60 MINUTE) AS CHARTTIME_P1,NULL AS STORETIME,VALUE,ITEMID
from `physionet-data.mimiciii_clinical.labevents`
where hadm_id = 100011 and itemid in (50809,50931)) t2
on t1.CHARTTIME = t2.CHARTTIME_P1 and t1.HADM_ID = t2.HADM_ID
order by t1.CHARTTIME;
```

<span ng-show="promiseResolved" ng-transclude="" aria-hidden="false" class="">
Row | HADM_ID | CHARTTIME_CHART | CHARTTIME_LAB_P1 | STORETIME | ITEMID_CHART | ITEMID_LAB | VALUE_CHART | VALUE_LAB | &nbsp;
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 100011 | 2177-08-29T06:09:00 | 2177-08-29T06:09:00 | 2177-08-29T07:39:00 | 220621 | 50931 | 112 | 113 | &nbsp;
2 | 100011 | 2177-08-29T13:34:00 | 2177-08-29T13:34:00 | 2177-08-29T15:49:00 | 220621 | 50931 | 133 | 133 | &nbsp;
3 | 100011 | 2177-08-30T00:50:00 | 2177-08-30T00:50:00 | 2177-08-30T01:41:00 | 220621 | 50931 | 160 | 160 | &nbsp;
4 | 100011 | 2177-08-31T01:49:00 | 2177-08-31T01:49:00 | 2177-08-31T02:47:00 | 220621 | 50931 | 136 | 136 | &nbsp;
5 | 100011 | 2177-09-01T03:13:00 | 2177-09-01T03:13:00 | 2177-09-01T03:54:00 | 220621 | 50931 | 112 | 112 | &nbsp;
6 | 100011 | 2177-09-02T01:40:00 | 2177-09-02T01:40:00 | 2177-09-02T02:30:00 | 220621 | 50931 | 136 | 136 | &nbsp;
7 | 100011 | 2177-09-03T00:53:00 | 2177-09-03T00:53:00 | 2177-09-03T01:36:00 | 220621 | 50931 | 119 | 119 | &nbsp;
8 | 100011 | 2177-09-04T01:08:00 | 2177-09-04T01:08:00 | 2177-09-04T02:06:00 | 220621 | 50931 | 125 | 125 | &nbsp;
9 | 100011 | 2177-09-05T02:32:00 | 2177-09-05T02:32:00 | 2177-09-05T03:30:00 | 220621 | 50931 | 150 | 150 | &nbsp;
10 | 100011 | 2177-09-06T01:58:00 | 2177-09-06T01:58:00 | 2177-09-06T03:16:00 | 220621 | 50931 | 128 | 128 | &nbsp;
11 | 100011 | 2177-09-07T02:12:00 | 2177-09-07T02:12:00 | 2177-09-07T03:20:00 | 220621 | 50931 | 118 | 118 | &nbsp;
12 | 100011 | 2177-09-08T01:59:00 | 2177-09-08T01:59:00 | 2177-09-08T02:57:00 | 220621 | 50931 | 123 | 123 | &nbsp;
13 | 100011 | 2177-09-09T01:52:00 | 2177-09-09T01:52:00 | 2177-09-09T02:36:00 | 220621 | 50931 | 126 | 126

</span>

Label is mimic-iii
(don't see the gear symbol - no permission I guess)

**Comment by tompollard** [comment] 2021-06-10 16:09
This looks like a duplicate of https://github.com/MIT-LCP/mimic-code/issues/784

**Comment by oizin** [comment] 2021-06-11 00:55
Thanks @tompollard, yes it is the same issue. Should have search '60 minutes' not just '1 hour'! So the chartevents time should be used as the time of the measurement in the case of these duplicated blood glucose measures. 

I guess the only other thing I would add is that if this is a bug it seems to have crept into the 'Curated Data for Describing Blood Glucose Management in the Intensive Care Unit' on physionet so I will email the data contact to let them know of the issue in case they weren't aware. I don't think there is a Github repo for that data?

(examples from the first few rows of the curated data - filtered to BLOOD - you can see four 1 hour lagged repeats)

SUBJECT_ID | HADM_ID | ICUSTAY_ID | LOS_ICU_days | first_ICU_stay | TIMER | STARTTIME | GLCTIMER | ENDTIME | INPUT | INPUT_HRS | INSULINTYPE | EVENT | GLC | GLCSOURCE | INFXSTOP
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
11861 | 192256 | 200010 | 1 | TRUE | 2132-08-05 02:22:00 UTC | 2132-08-05 02:22:00 UTC | &nbsp; | &nbsp; | &nbsp; | 127 | BLOOD | &nbsp;
11861 | 192256 | 200010 | 1 | TRUE | 2132-08-05 03:22:00 UTC | 2132-08-05 03:22:00 UTC | &nbsp; | &nbsp; | &nbsp; | 127 | BLOOD | &nbsp;
41710 | 181955 | 200028 | 3 | TRUE | 2133-10-29 18:03:00 UTC | 2133-10-29 18:03:00 UTC | &nbsp; | &nbsp; | &nbsp; | 171 | BLOOD | &nbsp;
41710 | 181955 | 200028 | 3 | TRUE | 2133-10-30 04:02:00 UTC | 2133-10-30 04:02:00 UTC | &nbsp; | &nbsp; | &nbsp; | 310 | BLOOD | &nbsp;
41710 | 181955 | 200028 | 3 | TRUE | 2133-10-30 05:02:00 UTC | 2133-10-30 05:02:00 UTC | &nbsp; | &nbsp; | &nbsp; | 310 | BLOOD | &nbsp;
41710 | 181955 | 200028 | 3 | TRUE | 2133-10-30 20:00:00 UTC | 2133-10-30 20:00:00 UTC | &nbsp; | &nbsp; | &nbsp; | 322 | BLOOD | &nbsp;
41710 | 181955 | 200028 | 3 | TRUE | 2133-10-30 21:00:00 UTC | 2133-10-30 21:00:00 UTC | &nbsp; | &nbsp; | &nbsp; | 322 | BLOOD | &nbsp;
41710 | 181955 | 200028 | 3 | TRUE | 2133-10-31 05:00:00 UTC | 2133-10-31 05:00:00 UTC | &nbsp; | &nbsp; | &nbsp; | 260 | BLOOD | &nbsp;
41710 | 181955 | 200028 | 3 | TRUE | 2133-10-31 06:00:00 UTC | 2133-10-31 06:00:00 UTC | &nbsp; | &nbsp; | &nbsp; | 260 | BLOOD | &nbsp;

**Comment by tompollard** [comment] 2021-06-11 15:15
> Should have search '60 minutes' not just '1 hour'! So the chartevents time should be used as the time of the measurement in the case of these duplicated blood glucose measures.

Don't worry, GitHub issues aren't very friendly for searches (especially when the issues have been closed). @briangow is investigating options for improving the way we document this kind of thing (e.g. using GitHub discussions).

> I guess the only other thing I would add is that if this is a bug it seems to have crept into the 'Curated Data for Describing Blood Glucose Management in the Intensive Care Unit' on physionet so I will email the data contact to let them know of the issue in case they weren't aware.

That's a good thought. The contact details should be at: https://physionet.org/content/glucose-management-mimic/1.0.1/. If necessary, they are able to release a new version with a fix (or a note highlighting the issue). Not sure whether or not there is a GitHub repo but Aldo will know. 

The issue has been fixed in MIMIC-IV, I believe.

**Closed** 2021-06-21 19:39 UTC
Labels: mimic-iii
