### ISSUE TITLE
In MIMIC-IV labevents table, there are a lot of entries with missing hadm_id. Can you check the issue?

### ISSUE THREAD

**Issue by baburz** [MIT-LCP/mimic-code#1703] opened 2024-02-01 15:29 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the online documentation: https://mimic.mit.edu/
    * Checked that your issue isn't already addressed: https://github.com/MIT-LCP/mimic-code/issues?utf8=%E2%9C%93&q=

### Description

Example entries: 
1,10000032,,45421181,51237,P28Z0X,2180-03-23 11:51:00,2180-03-23 15:15:00,1.4,1.4,,0.9,1.1,abnormal,ROUTINE,						 2,10000032,,45421181,51274,P28Z0X,2180-03-23 11:51:00,2180-03-23 15:15:00,___,15.1,sec,9.4,12.5,abnormal,ROUTINE,VERIFIED.						 3,10000032,,52958335,50853,P28Z0X,2180-03-23 11:51:00,2180-03-25 11:06:00,___,15,ng/mL,30,60,abnormal,ROUTINE,NEW ASSAY IN USE ___: DETECTS D2 AND D3 25-OH ACCURATELY.						 
4,10000032,,52958335,50861,P28Z0X,2180-03-23 11:51:00,2180-03-23 16:40:00,102,102,IU/L,0,40,abnormal,ROUTINE,						 5,10000032,,52958335,50862,P28Z0X,2180-03-23 11:51:00,2180-03-23 16:40:00,3.3,3.3,g/dL,3.5,5.2,abnormal,ROUTINE,

**Comment by tompollard** [comment] 2024-02-01 15:44
Duplicate of https://github.com/MIT-LCP/mimic-code/issues/1294

**Comment by alistairewj** [comment] 2024-02-01 15:54
Yes this is expected. Outpatient labs are included in MIMIC-IV, so the lack of an `hadm_id` indicates the lab was taken outside of the hospital. Do note that "outside of the hospital" can include the emergency department, which is technically a clinic, until the patient is admitted. If you care about timing, joining with `subject_id` and filters around `charttime` will get you a long way.

**Closed by alistairewj** 2024-02-01 15:54 UTC
